### ISSUE TITLE
Libraries not found for CUDA 11

### ISSUE THREAD

**Issue by lvotapka** [openmm/openmmexampleplugin#20]
I hate to bug you all with this problem, but I'm really at my wit's end at the moment.

I've built the latest version of OpenMM from source by cloning the openmm/openmm Github repository. I've done this many times before, but only recently started having this problem. I have Cuda 11 installed, and for the first time, I was getting an error that CUDA_CUDA_LIBRARY was NOTFOUND. So instead of running ccmake without any arguments, I ran 

cmake -DCMAKE_INSTALL_PREFIX=/home/lvotapka/bin/openmm -DCMAKE_LIBRARY_PATH=/usr/local/cuda/lib64/stubs ..

Since the directory /usr/local/cuda/lib64/stubs contains the libcuda.so file.

But now when I try to install a plugin (this one or any others), I get the following errors at the end of the make step:

[100%] Linking CXX executable TestCudaExampleForce
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: warning: libcuda.so.1, needed by /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so, not found (try using -rpath or -rpath-link)
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: warning: libcufft.so.10, needed by /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so, not found (try using -rpath or -rpath-link)
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuCtxSetLimit'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cufftPlan3d@libcufft.so.10'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuGetErrorName'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuCtxGetLimit'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuCtxDestroy_v2'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuCtxSetCurrent'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuMemcpyDtoD_v2'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuEventCreate'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuMemcpyDtoDAsync_v2'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cufftSetStream@libcufft.so.10'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cufftExecR2C@libcufft.so.10'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuDeviceGet'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuMemcpyDtoH_v2'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuFuncSetCacheConfig'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuMemFreeHost'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cufftExecC2R@libcufft.so.10'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuStreamCreate'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuMemAlloc_v2'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuProfilerStop'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuMemFree_v2'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuMemcpy'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuMemcpyDtoHAsync_v2'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cufftDestroy@libcufft.so.10'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuDriverGetVersion'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuDeviceCanAccessPeer'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuDeviceGetName'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuMemHostGetDevicePointer_v2'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cufftExecZ2D@libcufft.so.10'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuMemcpyHtoDAsync_v2'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuModuleLoad'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuCtxEnablePeerAccess'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuLaunchKernel'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuStreamWaitEvent'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuCtxSynchronize'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuModuleLoadDataEx'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuDeviceGetAttribute'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuDeviceGetCount'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuMemcpyHtoD_v2'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuMemcpyAsync'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cufftExecD2Z@libcufft.so.10'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuInit'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuEventSynchronize'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuEventRecord'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuCtxCreate_v2'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuModuleGetFunction'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuStreamSynchronize'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuCtxSetCacheConfig'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cufftGetVersion@libcufft.so.10'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuStreamDestroy_v2'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuEventDestroy_v2'
/home/lvotapka/miniconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: /home/lvotapka/bin/openmm/lib/plugins/libOpenMMCUDA.so: undefined reference to `cuMemHostAlloc'
collect2: error: ld returned 1 exit status
platforms/cuda/tests/CMakeFiles/TestCudaExampleForce.dir/build.make:98: recipe for target 'platforms/cuda/tests/TestCudaExampleForce' failed
make[2]: *** [platforms/cuda/tests/TestCudaExampleForce] Error 1
CMakeFiles/Makefile2:348: recipe for target 'platforms/cuda/tests/CMakeFiles/TestCudaExampleForce.dir/all' failed
make[1]: *** [platforms/cuda/tests/CMakeFiles/TestCudaExampleForce.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

I've been struggling for awhile to resolve this problem, even installing an older version of Cuda (10.2), to no avail. Any help or ideas would be much appreciated.

**Comment by peastman** [comment]
I don't think `CUDA_CUDA_LIBRARY` has any connection to `CMAKE_LIBRARY_PATH`.  The easiest thing to do is run `ccmake`.  Then you can see exactly which libraries aren't getting found and set the variables for them directly.

**Comment by lvotapka** [comment]
Yeah, strangely, the ccmake GUI will not let me set the CUDA_CUDA_LIBRARY value: as soon as I enter the correct directory, I hit 'c' to configure, but it somehow 'forgets' the value I entered and I get another CUDA_CUDA_LIBRARY was NOTFOUND error before I can generate.

It seems to work if I set CUDA_CUDA_LIBRARY value directly within the command line -D argument for 'cmake' to install OpenMM, and I can at least generate, however this doesn't seem to help the installation of the plugin, because I get the same errors listed above.

**Comment by lvotapka** [comment]
I was able to solve this problem.

Apparently, either trying to compile with CUDA 11 wasn't working, or a program I installed messed up my environmental variables or something, because when I backed up my files and reinstalled my operating system, and then installed CUDA 10.2, the OpenMM and example plugin built and compiled without a hitch.
